name: ses-ling
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - ipykernel
  - ipywidgets
  - numpy
  - pandas
  - geopandas
  - pygeos
  - jupyterlab
  - matplotlib
  - pyarrow
  - libpysal
  - pip:
      # local package
    - -e .
    - # external requirements
    - python-dotenv>=0.5.1
    - tqdm
    - plotly
    - seaborn
    - ray
    - rectangle-packer
    - pycld2
    - language_tool_python
    - git+https://github.com/TLouf/querier.git
    - memoization
